

name: build java application
on:
 push:
  branches:
  - master 
jobs:
 buildjob:
  runs-on: ubuntu-latest
  steps:
   - name: Clone the repository
     uses: actions/checkout@v4
   - name: Install java17
     uses: actions/setup-java@v4
     with: 
      distribution: 'temurin'
      java-version: '17'
      cache: 'maven'
   - name: build the java code
     run: mvn clean install package

