name: build java Application 
on: 
 push:
  branches:
   - master 
jobs:
  buildjob: 
   runs-on: ubuntu-latest
   steps: 
    - name: Clone the repo 
      uses: actions/checkout@v4
    - name: Install java 17
      uses: actions/setup-java@v4
      with: 
       java-version: '17'
       distribution: 'temurin'
       cache: maven
    - name: Scan the source code using sonarqube
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=sonar-jenkins-sonal-demo19june_sonar-jenkins-sonal-poject-19june -Dsonar.organization=sonar-jenkins-sonal-demo19june -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
